info:
  component: Cloud Native This is Zuul Server
server:
  port: 9020

spring:
  application:
    name: service-zuul
security:
    basic:
      enabled: false
    user:
      name: xifengjun
      password: 443596
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@service-eureka:9000/eureka/

zuul:
  routes:
    api-a:
        path: /api-a/**
        serviceId: service-ribbon
    api-b:
        path: /api-b/**
        serviceId: service-feign