info:
  component: Zwitscher Zuul Edge Server

server:
  port: 9012

hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000