spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.0.2:3306/pay
        username: jeken
        password: pay
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'ok'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  #mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.xfs.scm.**.mapper

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    com.netflix.discovery: ERROR
    org.springframework.cloud: ERROR
    org.springframework.web: DEBUG
    org.xfs.scm.manager: DEBUG
#    de.qaware.cloud.nativ.zwitscher: DEBUG
#
#management:
#  context-path: /admin
#
#eureka:
#  instance:
#    # register with IP addresses (required for deployment in Kubernetes?)
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 10
#    statusPageUrlPath: ${management.context-path}/info
#    healthCheckUrlPath: ${management.context-path}/health
#
#
#endpoints:
#  info:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    enabled: true
#    sensitive: false
